### PR TITLE
✨www.Theology101.church NextJS website first setup

### PR DESCRIPTION
**Pull request by Pinimes**
# Status
WIP

# Description

- setup Theology101.church site

# Trello card
https://trello.com/c/64RFDjIR

# Screenshot
theology101

### CODE REVIEW

**Comment by lleung030** [comment]
This looks really good Peniel keep up the good work. It looks exactly like the template and super clean.

**Comment by Pinimes** [comment]
Thank you lucas, it means a lot😊

**Comment by Pinimes** [comment]
This task was already done in PR#2 and it is a duplicate, so we are closing this PR

**Comment by Pinimes** [comment]
This task was already done in PR#2 and it is a duplicate, so we are closing this PR

**Pull request closed without merging**
